# Etapa de construcción
FROM node:14-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa final: Servir con Nginx
FROM nginx:alpine
# Copia la configuración personalizada de Nginx
COPY default.conf /etc/nginx/conf.d/default.conf
# Copia los archivos estáticos generados en la etapa build
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
